# Generated by Django 3.1.4 on 2021-01-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingPostcode',
            new_name='billingZip',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shippingPostcode',
            new_name='shippingAddress',
        ),
        migrations.AddField(
            model_name='order',
            name='shippingZip',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
