# Generated by Django 3.1.4 on 2021-01-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210118_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shippingCounty',
            new_name='shippingCountry',
        ),
    ]
