# Generated by Django 3.1.4 on 2021-01-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=300)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Order Total')),
                ('emailAddress', models.EmailField(blank=True, max_length=300, verbose_name='Email Address')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('billingName', models.CharField(blank=True, max_length=300)),
                ('billingAddress', models.CharField(blank=True, max_length=300)),
                ('billingCountry', models.CharField(blank=True, max_length=300)),
                ('billingCity', models.CharField(blank=True, max_length=300)),
                ('billingZip', models.CharField(blank=True, max_length=300)),
                ('shippingName', models.CharField(blank=True, max_length=300)),
                ('shippingAddress', models.CharField(blank=True, max_length=300)),
                ('shippingCountry', models.CharField(blank=True, max_length=300)),
                ('shippingCity', models.CharField(blank=True, max_length=300)),
                ('shippingZip', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
